export const reels = [
  {
    title: "雞排英雄",
    entitle: "Night Market Hero",
    type: "movie",
    url: "https://m.imdb.com/title/tt1887820/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_night%2520market",
    image: "r01.jpg",
  },
  {
    title: "大稻埕",
    entitle: "Twa-Tiu-Tiann",
    type: "movie",
    url: "https://m.imdb.com/title/tt3487082/?ref_=nv_sr_srsg_0_tt_1_nm_0_in_0_q_Twa-Tiu-Tiann",
    image: "r02.jpg",
  },
  {
    title: "狂徒",
    entitle: "The Scoundrels",
    type: "movie",
    url: "https://m.imdb.com/title/tt9081774/?ref_=ext_shr_lnk",
    image: "r03.jpg",
  },
  {
    title: "角頭2：王者再起",
    entitle: "Gatao 2: Rise of the King",
    type: "movie",
    url: "https://m.imdb.com/title/tt8324576/?ref_=ext_shr_lnk",
    image: "r04.jpg",
  },
  {
    title: "愛情算不算",
    entitle: "When Miracle Meets Maths",
    type: "movie",
    url: "https://m.imdb.com/title/tt5880820/?ref_=ext_shr_lnk",
    image: "r05.jpg",
  },
  {
    title: "五星級魚干女",
    entitle: "Welcome To The Happy Days",
    type: "movie",
    url: "https://m.imdb.com/title/tt4996668/?ref_=ext_shr_lnk",
    image: "r06.jpg",
  },
  {
    title: "西城童話",
    entitle: "The Mad King of Taipei Town",
    type: "movie",
    url: "https://m.imdb.com/title/tt6557116/?ref_=ext_shr_lnk",
    image: "r07.jpg",
  },
  {
    title: "角頭-大橋頭",
    entitle: "Gatao: Like Father Like Son",
    type: "movie",
    url: "https://m.imdb.com/title/tt32915791/?ref_=ext_shr_lnk",
    image: "r08.jpg",
  },
  {
    title: "雙城故事",
    entitle: "A Taiwanese Tale of Two Cities",
    type: "movie",
    url: "https://m.imdb.com/title/tt8893498/?ref_=ext_shr_lnk",
    image: "r09.jpg",
  },
  {
    title: "路～台灣Express～",
    entitle: "Ru~Taiwan Express",
    type: "movie",
    url: "https://m.imdb.com/title/tt11259980/?ref_=ext_shr_lnk",
    image: "r10.jpg",
  },
  {
    title: "第三佈局：塵沙惑",
    entitle: "Trinity of Shadow",
    type: "movie",
    url: "https://m.imdb.com/title/tt14845204/?ref_=ext_shr_lnk",
    image: "r11.jpg",
  },
  {
    title: "流氓蛋糕店",
    entitle: "Chocolat",
    type: "tv",
    url: "https://m.imdb.com/title/tt2337458/?ref_=ext_shr_lnk",
    image: "r12.jpg",
  },
  {
    title: "樂之路",
    entitle: "Road Less Traveled",
    type: "movie",
    url: "https://m.imdb.com/title/tt1205564/?ref_=ext_shr_lnk",
    image: "r13.jpg",
  },
  {
    title: "蔡依林- 大藝術家",
    entitle: "The Great Artist",
    type: "mv",
    url: "https://m.imdb.com/title/tt10333952/?ref_=ext_shr_lnk",
    image: "r14.jpg",
  },
  {
    title: "Fujii Kaze: Workin' Hard",
    entitle: "Working Hard",
    type: "mv",
    url: "https://m.imdb.com/title/tt28793141/?ref_=ext_shr_lnk",
    image: "r15.jpg",
  },
];

export const actors = [
  {
    name: "李淳",
    englishName: "Mason Lee",
    imdbUrl: "https://m.imdb.com/name/nm0497853",
    image: "a06.jpg",
  },
  {
    name: "張懷秋",
    englishName: "Harry Chang",
    imdbUrl: "https://m.imdb.com/name/nm3580247",
    image: "a03.jpg",
  },
  {
    name: "周厚安",
    englishName: "Andrew Chau",
    imdbUrl: "https://m.imdb.com/name/nm7563749",
    image: "a08.jpg",
  },
  {
    name: "鳳小岳",
    englishName: "Rhydian Vaughan",
    imdbUrl: "https://m.imdb.com/name/nm3120546",
    image: "a09.jpg",
  },
  {
    name: "王陽明",
    englishName: "Sunny Wang",
    imdbUrl: "https://m.imdb.com/name/nm5325301",
    image: "a11.jpg",
  },
  {
    name: "施銘帥",
    englishName: "Ming-Shuai Shih",
    imdbUrl: "https://m.imdb.com/name/nm6027485",
    image: "a12.jpg",
  },
  {
    name: "鄭人碩",
    englishName: "Jen-Shuo Cheng",
    imdbUrl: "https://m.imdb.com/name/nm7144002",
    image: "a13.jpg",
  },
  {
    name: "古斌",
    englishName: "Samuel Ku",
    imdbUrl: "https://m.imdb.com/name/nm6084330",
    image: "a10.jpg",
  },
  {
    name: "劉奕兒",
    englishName: "Eugenie Liu",
    imdbUrl: "https://m.imdb.com/name/nm8658823",
    image: "a01.jpg",
  },
  {
    name: "袁子芸",
    englishName: "Sonia Yuan",
    imdbUrl: "https://m.imdb.com/name/nm9880444",
    image: "a02.jpg",
  },
  {
    name: "曾沛慈",
    englishName: "Pets Tseng",
    imdbUrl: "https://m.imdb.com/name/nm6628253",
    image: "a07.jpg",
  },

  {
    name: "宋芸樺",
    englishName: "Vivian Sung",
    imdbUrl: "https://m.imdb.com/name/nm6718764",
    image: "a04.jpg",
  },
  {
    name: "紀培慧",
    englishName: "Teresa Daley",
    imdbUrl: "https://m.imdb.com/name/nm3632940",
    image: "a05.jpg",
  },
];
